@startuml class

class Produit {
   id
   nom
   prixAchat
   prixVente
   stock
   seuilStock
}

class Client {
   id
   nom
   telephone
   email
   limiteCredit
}

class Fournisseur {
   id
   nom
   telephone
   email
   adresse
}

class Commande {
     id
     dateCommande
     total
     statut
}

class LigneCommande {
     id
     quantite
     prixUnitaire
     sousTotal
}

class Dette {
     id
     montant
     montantRestant
     statut
     dateCreation
}

class Paiement {
     id
     montant
     datePaiement
     modePaiement
}

class Approvisionnement {
     id
     dateApprovisionnement
     total
     statut
}

class LigneApprovisionnement {
     id
     quantite
     prixUnitaire
     sousTotal
}

 

Client "1" -- "0..*" Commande

Commande "1" -- "1..*" LigneCommande

Produit "1" -- "0..*" LigneCommande

Commande "1" -- "0..1" Dette

Dette "1" -- "0..*" Paiement

Fournisseur "1" -- "0..*" Approvisionnement

Approvisionnement "1" -- "1..*" LigneApprovisionnement

Produit "1" -- "0..*" LigneApprovisionnement


@enduml